name: Pylint

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencieswith pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pylint
#    We disable this to test testing
#    - name: Analysing the code with pylint
#      run: |
#        pylint $(git ls-files '*.py')

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencieswith pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pytest
#    - name: run tests with pytest
#      run: pytest -l

  build: 
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: building image
      run: docker build . -t city-api:latest
    - name: publish docker image to ghcr.io
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        username: "WoodenMaiden"
        password: ${{ github.token }}
        repository: woodenmaiden/cicdtp
        tags: latest
