name: Pylint

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            core.setOutput('no-v', no_v)

      - name: publish docker image to ghcr.io
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.TOKEN_GHCR }}
          repository: woodenmaiden/cicd-tp #hard coded because of upper case
          tags: ${{ steps.set_version.outputs.no_v }}
